//
// AdminPartnerListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminPartnerListResponse: Codable, Hashable {

    public var partners: [Partner]
    public var pagination: Pagination

    public init(partners: [Partner], pagination: Pagination) {
        self.partners = partners
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case partners
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(partners, forKey: .partners)
        try container.encode(pagination, forKey: .pagination)
    }
}

