//
// AdminPartnerCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminPartnerCreateRequest: Codable, Hashable {

    public var name: String?
    public var label: String?
    public var email: String
    /** Двойной sha256 от строки с паролем */
    public var password: String

    public init(name: String? = nil, label: String? = nil, email: String, password: String) {
        self.name = name
        self.label = label
        self.email = email
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case label
        case email
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
    }
}

