//
// AppliedDiscountItemDiscountSumByOrderItemIdValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppliedDiscountItemDiscountSumByOrderItemIdValue: Codable, Hashable {

    public var id: String?
    public var discount: Double?

    public init(id: String? = nil, discount: Double? = nil) {
        self.id = id
        self.discount = discount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case discount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(discount, forKey: .discount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AppliedDiscountItemDiscountSumByOrderItemIdValue: Identifiable {}
