//
// AuthRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Авторизационный запрос */
public struct AuthRequest: Codable, Hashable {

    /** Логин */
    public var login: String
    /** Пароль (двойной sha256 от строки с паролем) */
    public var password: String

    public init(login: String, password: String) {
        self.login = login
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case login
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(login, forKey: .login)
        try container.encode(password, forKey: .password)
    }
}

