//
// AuthPhoneRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Авторизационный запрос по номеру телефона */
public struct AuthPhoneRequest: Codable, Hashable {

    /** Номер телефона (только цифры, без '+', начиная с 7). Пока ожидаем только рос номера */
    public var phone: String

    public init(phone: String) {
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phone, forKey: .phone)
    }
}

