//
// AvalilableWeekDays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Дни недели */
public struct AvalilableWeekDays: Codable, Hashable {

    /** Понедельник */
    public var monday: Bool?
    /** Вторник */
    public var tuesday: Bool?
    /** Среда */
    public var wednesday: Bool?
    /** Четверг */
    public var thursday: Bool?
    /** Пятница */
    public var friday: Bool?
    /** Суббота */
    public var saturday: Bool?
    /** Воскресенье */
    public var sunday: Bool?

    public init(monday: Bool? = nil, tuesday: Bool? = nil, wednesday: Bool? = nil, thursday: Bool? = nil, friday: Bool? = nil, saturday: Bool? = nil, sunday: Bool? = nil) {
        self.monday = monday
        self.tuesday = tuesday
        self.wednesday = wednesday
        self.thursday = thursday
        self.friday = friday
        self.saturday = saturday
        self.sunday = sunday
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case monday
        case tuesday
        case wednesday
        case thursday
        case friday
        case saturday
        case sunday
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(monday, forKey: .monday)
        try container.encodeIfPresent(tuesday, forKey: .tuesday)
        try container.encodeIfPresent(wednesday, forKey: .wednesday)
        try container.encodeIfPresent(thursday, forKey: .thursday)
        try container.encodeIfPresent(friday, forKey: .friday)
        try container.encodeIfPresent(saturday, forKey: .saturday)
        try container.encodeIfPresent(sunday, forKey: .sunday)
    }
}

