//
// BonusTransactionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип транзакции */
public enum BonusTransactionType: String, Codable, CaseIterable {
    case increase = "increase"
    case decrease = "decrease"
}
