//
// BrandConfigDeletePicturesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BrandConfigDeletePicturesRequest: Codable, Hashable {

    public var pictures: [String]?

    public init(pictures: [String]? = nil) {
        self.pictures = pictures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pictures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pictures, forKey: .pictures)
    }
}

