//
// CategoryCreateIconResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Запрос для добавления картинки категории */
public struct CategoryCreateIconResponse: Codable, Hashable {

    public var category: MenuCategory?

    public init(category: MenuCategory? = nil) {
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
    }
}

