//
// ClientOrdersListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientOrdersListResponse: Codable, Hashable {

    public var orders: [Order]

    public init(orders: [Order]) {
        self.orders = orders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orders
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orders, forKey: .orders)
    }
}

