//
// ClientLoyaltyDebitRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientLoyaltyDebitRequest: Codable, Hashable {

    /** Количество баллов на списание, в копейках */
    public var amount: Int64?
    /** Полное списание баллов (либо полная оплата заказа, либо списание всех баллов). Имеет приоритет перед amount */
    public var full: Bool?

    public init(amount: Int64? = nil, full: Bool? = nil) {
        self.amount = amount
        self.full = full
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case full
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(full, forKey: .full)
    }
}

