//
// EmployeeRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Роль сотрудника */
public enum EmployeeRole: String, Codable, CaseIterable {
    case manager = "manager"
    case waiter = "waiter"
}
