//
// EmployeeCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeCreateResponse: Codable, Hashable {

    public var id: Int64?
    public var email: String?
    public var phone: String?
    public var role: EmployeeRole
    public var isBlocked: Bool?
    public var isDeleted: Bool?
    /** id ресторана к которому привязан сотрудник */
    public var outletId: Int64
    /** Наименование ресторана к которому привязан сотрудник */
    public var outlet: String?
    /** Имя */
    public var firstName: String?
    /** Фамилия */
    public var lastName: String?
    /** Отчество при наличии */
    public var middleName: String?

    public init(id: Int64? = nil, email: String? = nil, phone: String? = nil, role: EmployeeRole, isBlocked: Bool? = nil, isDeleted: Bool? = nil, outletId: Int64, outlet: String? = nil, firstName: String? = nil, lastName: String? = nil, middleName: String? = nil) {
        self.id = id
        self.email = email
        self.phone = phone
        self.role = role
        self.isBlocked = isBlocked
        self.isDeleted = isDeleted
        self.outletId = outletId
        self.outlet = outlet
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case phone
        case role
        case isBlocked = "is_blocked"
        case isDeleted = "is_deleted"
        case outletId = "outlet_id"
        case outlet
        case firstName = "first_name"
        case lastName = "last_name"
        case middleName = "middle_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(isBlocked, forKey: .isBlocked)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encode(outletId, forKey: .outletId)
        try container.encodeIfPresent(outlet, forKey: .outlet)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(middleName, forKey: .middleName)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeCreateResponse: Identifiable {}
