//
// EmployeeListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeListResponse: Codable, Hashable {

    public var employees: [Employee]
    public var pagination: Pagination

    public init(employees: [Employee], pagination: Pagination) {
        self.employees = employees
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case employees
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(employees, forKey: .employees)
        try container.encode(pagination, forKey: .pagination)
    }
}

