//
// FilterType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип фильтрации - вернуть записи, для которых условие выполняется или не выполняется */
public enum FilterType: String, Codable, CaseIterable {
    case accept = "accept"
    case reject = "reject"
}
