//
// FullName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FullName: Codable, Hashable {

    /** Имя */
    public var firstName: String?
    /** Фамилия */
    public var lastName: String?
    /** Отчество при наличии */
    public var middleName: String?

    public init(firstName: String? = nil, lastName: String? = nil, middleName: String? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case middleName = "middle_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(middleName, forKey: .middleName)
    }
}

