//
// Gender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Пол */
public enum Gender: String, Codable, CaseIterable {
    case other = "other"
    case male = "male"
    case female = "female"
}
