//
// GeocodingReverseResponseSuggestionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeocodingReverseResponseSuggestionsInner: Codable, Hashable {

    /** Форматированный адрес */
    public var value: String
    public var unrestrictedValue: String
    public var data: GeoData

    public init(value: String, unrestrictedValue: String, data: GeoData) {
        self.value = value
        self.unrestrictedValue = unrestrictedValue
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case unrestrictedValue = "unrestricted_value"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(unrestrictedValue, forKey: .unrestrictedValue)
        try container.encode(data, forKey: .data)
    }
}

