//
// GeocodingDirectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeocodingDirectResponse: Codable, Hashable {

    public var addresses: [GeoData]?

    public init(addresses: [GeoData]? = nil) {
        self.addresses = addresses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addresses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addresses, forKey: .addresses)
    }
}

