//
// Guest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Guest: Codable, Hashable {

    public var id: UUID?
    public var name: String?
    /** Guest's rank in order. */
    public var rank: Int?

    public init(id: UUID? = nil, name: String? = nil, rank: Int? = nil) {
        self.id = id
        self.name = name
        self.rank = rank
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case rank = "Rank"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(rank, forKey: .rank)
    }
}

