//
// IikoCard51CouponInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IikoCard51CouponInfo: Codable, Hashable {

    /** Card series */
    public var series: String?
    /** Card number */
    public var number: String?
    /** Whether coupon is applied */
    public var applied: Bool?

    public init(series: String? = nil, number: String? = nil, applied: Bool? = nil) {
        self.series = series
        self.number = number
        self.applied = applied
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case series = "Series"
        case number = "Number"
        case applied = "Applied"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(applied, forKey: .applied)
    }
}

