//
// IikoTerminal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** iiko терминал */
public struct IikoTerminal: Codable, Hashable {

    public var id: Int64?
    public var name: String?
    public var payments: [IikoPayment]?
    public var isDeleted: Bool?

    public init(id: Int64? = nil, name: String? = nil, payments: [IikoPayment]? = nil, isDeleted: Bool? = nil) {
        self.id = id
        self.name = name
        self.payments = payments
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case payments
        case isDeleted = "is_deleted"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(payments, forKey: .payments)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension IikoTerminal: Identifiable {}
