//
// ItemCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemCategory: Codable, Hashable {

    public var id: UUID?
    public var code: String?

    public init(id: UUID? = nil, code: String? = nil) {
        self.id = id
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case code = "Code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

