//
// LoyaltyLvlPictureDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoyaltyLvlPictureDeleteResponse: Codable, Hashable {

    public var loyaltyLvls: [LoyaltyLevel]?

    public init(loyaltyLvls: [LoyaltyLevel]? = nil) {
        self.loyaltyLvls = loyaltyLvls
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loyaltyLvls = "loyalty_lvls"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(loyaltyLvls, forKey: .loyaltyLvls)
    }
}

