//
// LoyaltyLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Уровень программы лояльности */
public struct LoyaltyLevel: Codable, Hashable {

    public var id: Int64?
    public var name: String
    /** Начиная с какой суммы действует уровень, включая. В копейках */
    public var min: Int64
    /** До какой суммы действует уровень, не включая. В копейках. У последнего уровня 0 */
    public var max: Int64
    /** Процент кэшбека. В %*10000 */
    public var percent: Int64
    /** картинка уровня */
    public var picture: String?

    public init(id: Int64? = nil, name: String, min: Int64, max: Int64, percent: Int64, picture: String? = nil) {
        self.id = id
        self.name = name
        self.min = min
        self.max = max
        self.percent = percent
        self.picture = picture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case min
        case max
        case percent
        case picture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(min, forKey: .min)
        try container.encode(max, forKey: .max)
        try container.encode(percent, forKey: .percent)
        try container.encodeIfPresent(picture, forKey: .picture)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension LoyaltyLevel: Identifiable {}
