//
// MenuCategoriesListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenuCategoriesListResponse: Codable, Hashable {

    public var categories: [MenuCategory]

    public init(categories: [MenuCategory]) {
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categories, forKey: .categories)
    }
}

