//
// MenuCategoryListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenuCategoryListResponse: Codable, Hashable {

    public var categories: [MenuCategory]
    public var pagination: Pagination

    public init(categories: [MenuCategory], pagination: Pagination) {
        self.categories = categories
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categories, forKey: .categories)
        try container.encode(pagination, forKey: .pagination)
    }
}

