//
// MenuItemListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenuItemListResponse: Codable, Hashable {

    public var menuItems: [MenuItem]
    public var pagination: Pagination

    public init(menuItems: [MenuItem], pagination: Pagination) {
        self.menuItems = menuItems
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case menuItems
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(menuItems, forKey: .menuItems)
        try container.encode(pagination, forKey: .pagination)
    }
}

