//
// MenusListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenusListResponse: Codable, Hashable {

    public var menus: [Menu]

    public init(menus: [Menu]) {
        self.menus = menus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case menus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(menus, forKey: .menus)
    }
}

