//
// MenuItemToCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenuItemToCategory: Codable, Hashable {

    /** ID блюда */
    public var menuItemId: Int
    /** ID категории */
    public var categoryId: Int
    /** ID меню */
    public var menuId: Int
    /** Позиция блюда в категории */
    public var position: Int?

    public init(menuItemId: Int, categoryId: Int, menuId: Int, position: Int? = nil) {
        self.menuItemId = menuItemId
        self.categoryId = categoryId
        self.menuId = menuId
        self.position = position
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case menuItemId = "menu_item_id"
        case categoryId = "category_id"
        case menuId = "menu_id"
        case position
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(menuItemId, forKey: .menuItemId)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(menuId, forKey: .menuId)
        try container.encodeIfPresent(position, forKey: .position)
    }
}

