//
// Menu.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Меню ресторана */
public struct Menu: Codable, Hashable {

    public var id: Int64?
    /** Название */
    public var name: String?
    /** id партнера */
    public var partnerId: Int64?
    /** id ресторана */
    public var outletId: Int64?
    /** Категории в меню */
    public var categories: [MenuCategory]?

    public init(id: Int64? = nil, name: String? = nil, partnerId: Int64? = nil, outletId: Int64? = nil, categories: [MenuCategory]? = nil) {
        self.id = id
        self.name = name
        self.partnerId = partnerId
        self.outletId = outletId
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case partnerId = "partner_id"
        case outletId = "outlet_id"
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(partnerId, forKey: .partnerId)
        try container.encodeIfPresent(outletId, forKey: .outletId)
        try container.encodeIfPresent(categories, forKey: .categories)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Menu: Identifiable {}
