//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Типовая ошибка */
public struct ModelErrorResponse: Codable, Hashable {

    /** Код ошибки */
    public var code: Int
    /** Сообщение ошибки */
    public var message: String
    /** Дополнительные детали */
    public var detail: String
    /** Локализованное сообщение об ошибке */
    public var localizedMessage: String?

    public init(code: Int, message: String, detail: String, localizedMessage: String? = nil) {
        self.code = code
        self.message = message
        self.detail = detail
        self.localizedMessage = localizedMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case detail
        case localizedMessage = "localized_message"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(localizedMessage, forKey: .localizedMessage)
    }
}

