//
// OrdersPaymentByPointsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrdersPaymentByPointsResponse: Codable, Hashable {

    /** сколько баллов доступно для списания (актуальное значение) */
    public var pointsAvailable: Double
    /** Успех, баллы списаны (или не списаны) */
    public var success: Bool

    public init(pointsAvailable: Double, success: Bool) {
        self.pointsAvailable = pointsAvailable
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pointsAvailable = "points_available"
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pointsAvailable, forKey: .pointsAvailable)
        try container.encode(success, forKey: .success)
    }
}

