//
// OrderEvents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OrderEvents: String, Codable, CaseIterable {
    case created = "Created"
    case updated = "Updated"
    case removed = "Removed"
}
