//
// OrdersChekinResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrdersChekinResponse: Codable, Hashable {

    public var client: Client?
    /** оплата заказа баллами. Например 120.50 рублей */
    public var paymentInPoints: Double?

    public init(client: Client? = nil, paymentInPoints: Double? = nil) {
        self.client = client
        self.paymentInPoints = paymentInPoints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case client
        case paymentInPoints = "payment_in_points"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(client, forKey: .client)
        try container.encodeIfPresent(paymentInPoints, forKey: .paymentInPoints)
    }
}

