//
// OrdersPaymentByPointsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrdersPaymentByPointsRequest: Codable, Hashable {

    /** сколько баллов списывается в заказ */
    public var points: Double

    public init(points: Double) {
        self.points = points
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case points
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(points, forKey: .points)
    }
}

