//
// OrdersEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrdersEventRequest: Codable, Hashable {

    public var event: OrderEvents
    public var order: IikoOrder

    public init(event: OrderEvents, order: IikoOrder) {
        self.event = event
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(event, forKey: .event)
        try container.encode(order, forKey: .order)
    }
}

