//
// OutletListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OutletListRequest: Codable, Hashable {

    /** Фильтрация по параметрам */
    public var filter: [OutletListRequestFilterInner]?
    /** Поиск по параметрам */
    public var search: [OutletListRequestSearchInner]?
    public var pagination: Pagination

    public init(filter: [OutletListRequestFilterInner]? = nil, search: [OutletListRequestSearchInner]? = nil, pagination: Pagination) {
        self.filter = filter
        self.search = search
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case search
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(search, forKey: .search)
        try container.encode(pagination, forKey: .pagination)
    }
}

