//
// OutletListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OutletListResponse: Codable, Hashable {

    public var outlets: [Outlet]
    public var pagination: Pagination

    public init(outlets: [Outlet], pagination: Pagination) {
        self.outlets = outlets
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outlets
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(outlets, forKey: .outlets)
        try container.encode(pagination, forKey: .pagination)
    }
}

