//
// OutletListRequestFilterInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OutletListRequestFilterInner: Codable, Hashable {

    public enum FilterParameter: String, Codable, CaseIterable {
        case inLoyalty = "in_loyalty"
        case isDeleted = "is_deleted"
        case isVisibleOnMap = "is_visible_on_map"
        case partnerId = "partner_id"
    }
    /** Параметр, по которому осуществляется фильтрация.   in_loyalty - Добавление в лояльность. value_group: none;   is_deleted - Удаленные из iiko. value_group: none;   is_visible_on_map - Видимость на карте. value_group: none;   partner_id - Айди партнера. value_type: int64, value_group: single;  */
    public var filterParameter: FilterParameter
    public var inputValue: [FilterInputValueInner]?
    public var valueGroup: FilterValueGroup
    public var filterType: FilterType

    public init(filterParameter: FilterParameter, inputValue: [FilterInputValueInner]? = nil, valueGroup: FilterValueGroup, filterType: FilterType) {
        self.filterParameter = filterParameter
        self.inputValue = inputValue
        self.valueGroup = valueGroup
        self.filterType = filterType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filterParameter = "filter_parameter"
        case inputValue = "input_value"
        case valueGroup = "value_group"
        case filterType = "filter_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filterParameter, forKey: .filterParameter)
        try container.encodeIfPresent(inputValue, forKey: .inputValue)
        try container.encode(valueGroup, forKey: .valueGroup)
        try container.encode(filterType, forKey: .filterType)
    }
}

