//
// OutletToPosterDeleteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OutletToPosterDeleteRequest: Codable, Hashable {

    /** ID афиши */
    public var posterId: Int64
    /** ID ресторана */
    public var outletId: Int64
    /** дата публикации афиши */
    public var publicDate: Int64?
    /** дата начала мероприятия/афиши */
    public var startDate: Int64?
    /** дата окончания мероприятия/афиши */
    public var finishDate: Int64?

    public init(posterId: Int64, outletId: Int64, publicDate: Int64? = nil, startDate: Int64? = nil, finishDate: Int64? = nil) {
        self.posterId = posterId
        self.outletId = outletId
        self.publicDate = publicDate
        self.startDate = startDate
        self.finishDate = finishDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case posterId = "poster_id"
        case outletId = "outlet_id"
        case publicDate = "public_date"
        case startDate = "start_date"
        case finishDate = "finish_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(posterId, forKey: .posterId)
        try container.encode(outletId, forKey: .outletId)
        try container.encodeIfPresent(publicDate, forKey: .publicDate)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(finishDate, forKey: .finishDate)
    }
}

