//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pagination: Codable, Hashable {

    /** Всего элементов */
    public var total: Int?
    /** Номер страницы, начиная с 0 */
    public var page: Int
    /** Размер страницы */
    public var pageSize: Int

    public init(total: Int? = nil, page: Int, pageSize: Int) {
        self.total = total
        self.page = page
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case page
        case pageSize = "page_size"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encode(page, forKey: .page)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

