//
// PartnerClientListRequestSearchInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Поиск по имени/id/телефону */
public struct PartnerClientListRequestSearchInner: Codable, Hashable {

    public enum SearchParameter: String, Codable, CaseIterable {
        case fullSearch = "full_search"
    }
    /** Параметр, по которому осуществляется поиск full_search - поиск по id, phone и name или surname нужно учитывать, что номера начинаются с '7'  */
    public var searchParameter: SearchParameter
    /** Значение для поиска, введенное пользователем */
    public var inputValue: String

    public init(searchParameter: SearchParameter, inputValue: String) {
        self.searchParameter = searchParameter
        self.inputValue = inputValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchParameter = "search_parameter"
        case inputValue = "input_value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(searchParameter, forKey: .searchParameter)
        try container.encode(inputValue, forKey: .inputValue)
    }
}

