//
// PartnerSetIikoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartnerSetIikoRequest: Codable, Hashable {

    /** iiko api key для стягивания всей инфы из айко.  Обязательный для заполняния после создания партнера.  Факт создания контролировать полем presence_iiko_key в Partner. При последующих запросах добавляется в массив ключей  */
    public var iikoKey: String

    public init(iikoKey: String) {
        self.iikoKey = iikoKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iikoKey = "iiko_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(iikoKey, forKey: .iikoKey)
    }
}

