//
// PartnerClientUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartnerClientUpdateRequest: Codable, Hashable {

    /** Заметка о клиенте */
    public var note: String?

    public init(note: String? = nil) {
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

