//
// PartnerClientBlockRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartnerClientBlockRequest: Codable, Hashable {

    /** Блокировка */
    public var block: Bool?

    public init(block: Bool? = nil) {
        self.block = block
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case block
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(block, forKey: .block)
    }
}

