//
// PosterListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PosterListRequest: Codable, Hashable {

    /** Фильтрация по параметрам */
    public var filter: [PosterListRequestFilterInner]?
    /** Поиск по параметрам */
    public var search: [PosterListRequestSearchInner]?
    public var sort: PosterListRequestSort?
    public var pagination: Pagination

    public init(filter: [PosterListRequestFilterInner]? = nil, search: [PosterListRequestSearchInner]? = nil, sort: PosterListRequestSort? = nil, pagination: Pagination) {
        self.filter = filter
        self.search = search
        self.sort = sort
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case search
        case sort
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(search, forKey: .search)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encode(pagination, forKey: .pagination)
    }
}

