//
// PosterListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PosterListResponse: Codable, Hashable {

    public var posters: [Poster]
    public var pagination: Pagination

    public init(posters: [Poster], pagination: Pagination) {
        self.posters = posters
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case posters
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(posters, forKey: .posters)
        try container.encode(pagination, forKey: .pagination)
    }
}

