//
// PosterCreateImagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Запрос для добавления картинки/ок к афише */
public struct PosterCreateImagesResponse: Codable, Hashable {

    public var images: [String]?

    public init(images: [String]? = nil) {
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

