//
// PriceCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PriceCategory: Codable, Hashable {

    public var id: UUID?
    /** Name of price category. */
    public var name: String?
    /** Is this item deleted. */
    public var deleted: Bool?
    /** Unique price category code. */
    public var code: String?
    /** Can price category be applied to order manually. */
    public var canApplyManually: Bool?

    public init(id: UUID? = nil, name: String? = nil, deleted: Bool? = nil, code: String? = nil, canApplyManually: Bool? = nil) {
        self.id = id
        self.name = name
        self.deleted = deleted
        self.code = code
        self.canApplyManually = canApplyManually
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case deleted = "Deleted"
        case code = "Code"
        case canApplyManually = "CanApplyManually"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(deleted, forKey: .deleted)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(canApplyManually, forKey: .canApplyManually)
    }
}

