//
// RefCodesExistenceCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RefCodesExistenceCheckResponse: Codable, Hashable {

    /** реф кода не существует */
    public var notExist: Bool?
    /** реф код существует */
    public var exist: Bool?
    /** заблокирован */
    public var blocked: Bool?

    public init(notExist: Bool? = nil, exist: Bool? = nil, blocked: Bool? = nil) {
        self.notExist = notExist
        self.exist = exist
        self.blocked = blocked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notExist = "not_exist"
        case exist
        case blocked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notExist, forKey: .notExist)
        try container.encodeIfPresent(exist, forKey: .exist)
        try container.encodeIfPresent(blocked, forKey: .blocked)
    }
}

