//
// RefCodesCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RefCodesCreateRequest: Codable, Hashable {

    /** код */
    public var code: String
    /** количество начисляемых баллов *100 */
    public var pointAmount: Int64
    /** примечание */
    public var note: String
    /** заблокирован или нет */
    public var isBlocked: Bool

    public init(code: String, pointAmount: Int64, note: String, isBlocked: Bool) {
        self.code = code
        self.pointAmount = pointAmount
        self.note = note
        self.isBlocked = isBlocked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case pointAmount = "point_amount"
        case note
        case isBlocked = "is_blocked"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(pointAmount, forKey: .pointAmount)
        try container.encode(note, forKey: .note)
        try container.encode(isBlocked, forKey: .isBlocked)
    }
}

