//
// ReviewUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviewUpdateRequest: Codable, Hashable {

    /** Виден ли отзыв */
    public var visible: Bool?

    public init(visible: Bool? = nil) {
        self.visible = visible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case visible
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(visible, forKey: .visible)
    }
}

