//
// ReviewListRequestSort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Сортировка по параметрам */
public struct ReviewListRequestSort: Codable, Hashable {

    public enum SortParameter: String, Codable, CaseIterable {
        case createdAt = "created_at"
    }
    /** Параметр, по которому осуществляется сортировка created_at - по дате создания  */
    public var sortParameter: SortParameter
    public var sortType: SortType

    public init(sortParameter: SortParameter, sortType: SortType) {
        self.sortParameter = sortParameter
        self.sortType = sortType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sortParameter = "sort_parameter"
        case sortType = "sort_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sortParameter, forKey: .sortParameter)
        try container.encode(sortType, forKey: .sortType)
    }
}

