//
// ReviewListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviewListResponse: Codable, Hashable {

    public var reviews: [Review]
    public var pagination: Pagination

    public init(reviews: [Review], pagination: Pagination) {
        self.reviews = reviews
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reviews
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reviews, forKey: .reviews)
        try container.encode(pagination, forKey: .pagination)
    }
}

