//
// SetListPaymentsForTerminalRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetListPaymentsForTerminalRequest: Codable, Hashable {

    public var terminalId: Int64
    /** Список в котором передать все привязанные платежи к терминалу (старый стейт полностью удалится) */
    public var payments: [SetListPaymentsForTerminalRequestPaymentsInner]

    public init(terminalId: Int64, payments: [SetListPaymentsForTerminalRequestPaymentsInner]) {
        self.terminalId = terminalId
        self.payments = payments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case terminalId = "terminal_id"
        case payments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(terminalId, forKey: .terminalId)
        try container.encode(payments, forKey: .payments)
    }
}

