//
// SortType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип сортировки (по возрастанию или по убыванию) */
public enum SortType: String, Codable, CaseIterable {
    case asc = "asc"
    case desc = "desc"
}
