//
// TaxCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaxCategory: Codable, Hashable {

    public var id: UUID?
    public var name: String?
    public var vatPercent: Double?
    public var isCalculated: Bool?

    public init(id: UUID? = nil, name: String? = nil, vatPercent: Double? = nil, isCalculated: Bool? = nil) {
        self.id = id
        self.name = name
        self.vatPercent = vatPercent
        self.isCalculated = isCalculated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case vatPercent = "VatPercent"
        case isCalculated = "IsCalculated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(vatPercent, forKey: .vatPercent)
        try container.encodeIfPresent(isCalculated, forKey: .isCalculated)
    }
}

