//
// TimeFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimeFilter: Codable, Hashable {

    public enum Modificator: String, Codable, CaseIterable {
        case gt = "GT"
        case lt = "LT"
        case eq = "EQ"
    }
    public var time: Int64?
    public var modificator: Modificator?

    public init(time: Int64? = nil, modificator: Modificator? = nil) {
        self.time = time
        self.modificator = modificator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case modificator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(modificator, forKey: .modificator)
    }
}

