//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserResponse: Codable, Hashable {

    public var role: UserRole
    public var partner: Partner?
    public var client: Client?
    public var employee: Employee?
    public var admin: Admin?

    public init(role: UserRole, partner: Partner? = nil, client: Client? = nil, employee: Employee? = nil, admin: Admin? = nil) {
        self.role = role
        self.partner = partner
        self.client = client
        self.employee = employee
        self.admin = admin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case partner
        case client
        case employee
        case admin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(partner, forKey: .partner)
        try container.encodeIfPresent(client, forKey: .client)
        try container.encodeIfPresent(employee, forKey: .employee)
        try container.encodeIfPresent(admin, forKey: .admin)
    }
}

