//
// UserRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Роль пользователя */
public enum UserRole: String, Codable, CaseIterable {
    case admin = "admin"
    case client = "client"
    case partner = "partner"
    case employee = "employee"
}
