import SwiftUI

extension Font {
    
    private static func font(_ weight: Font.Weight, _ size: CGFloat) -> Font {
        return .system(size: size, weight: weight, design: .default)
    }

    // MARK: –– Light
    static let light10: Font = font(.light, 10)
    static let light11: Font = font(.light, 11)
    static let light12: Font = font(.light, 12)
    static let light13: Font = font(.light, 13)
    static let light14: Font = font(.light, 14)
    static let light15: Font = font(.light, 15)
    static let light16: Font = font(.light, 16)
    static let light17: Font = font(.light, 17)
    static let light18: Font = font(.light, 18)
    static let light19: Font = font(.light, 19)
    static let light20: Font = font(.light, 20)
    static let light21: Font = font(.light, 21)
    static let light22: Font = font(.light, 22)
    static let light23: Font = font(.light, 23)
    static let light24: Font = font(.light, 24)
    static let light25: Font = font(.light, 25)
    static let light26: Font = font(.light, 26)
    static let light27: Font = font(.light, 27)
    static let light28: Font = font(.light, 28)
    static let light29: Font = font(.light, 29)
    static let light30: Font = font(.light, 30)
    static let light31: Font = font(.light, 31)
    static let light32: Font = font(.light, 32)
    static let light33: Font = font(.light, 33)
    static let light34: Font = font(.light, 34)
    static let light35: Font = font(.light, 35)
    static let light36: Font = font(.light, 36)

    // MARK: –– Regular
    static let regular10: Font = font(.regular, 10)
    static let regular11: Font = font(.regular, 11)
    static let regular12: Font = font(.regular, 12)
    static let regular13: Font = font(.regular, 13)
    static let regular14: Font = font(.regular, 14)
    static let regular15: Font = font(.regular, 15)
    static let regular16: Font = font(.regular, 16)
    static let regular17: Font = font(.regular, 17)
    static let regular18: Font = font(.regular, 18)
    static let regular19: Font = font(.regular, 19)
    static let regular20: Font = font(.regular, 20)
    static let regular21: Font = font(.regular, 21)
    static let regular22: Font = font(.regular, 22)
    static let regular23: Font = font(.regular, 23)
    static let regular24: Font = font(.regular, 24)
    static let regular25: Font = font(.regular, 25)
    static let regular26: Font = font(.regular, 26)
    static let regular27: Font = font(.regular, 27)
    static let regular28: Font = font(.regular, 28)
    static let regular29: Font = font(.regular, 29)
    static let regular30: Font = font(.regular, 30)
    static let regular31: Font = font(.regular, 31)
    static let regular32: Font = font(.regular, 32)
    static let regular33: Font = font(.regular, 33)
    static let regular34: Font = font(.regular, 34)
    static let regular35: Font = font(.regular, 35)
    static let regular36: Font = font(.regular, 36)
    
    // MARK: –– Medium
    static let medium10: Font = font(.medium, 10)
    static let medium11: Font = font(.medium, 11)
    static let medium12: Font = font(.medium, 12)
    static let medium13: Font = font(.medium, 13)
    static let medium14: Font = font(.medium, 14)
    static let medium15: Font = font(.medium, 15)
    static let medium16: Font = font(.medium, 16)
    static let medium17: Font = font(.medium, 17)
    static let medium18: Font = font(.medium, 18)
    static let medium19: Font = font(.medium, 19)
    static let medium20: Font = font(.medium, 20)
    static let medium21: Font = font(.medium, 21)
    static let medium22: Font = font(.medium, 22)
    static let medium23: Font = font(.medium, 23)
    static let medium24: Font = font(.medium, 24)
    static let medium25: Font = font(.medium, 25)
    static let medium26: Font = font(.medium, 26)
    static let medium27: Font = font(.medium, 27)
    static let medium28: Font = font(.medium, 28)
    static let medium29: Font = font(.medium, 29)
    static let medium30: Font = font(.medium, 30)
    static let medium31: Font = font(.medium, 31)
    static let medium32: Font = font(.medium, 32)
    static let medium33: Font = font(.medium, 33)
    static let medium34: Font = font(.medium, 34)
    static let medium35: Font = font(.medium, 35)
    static let medium36: Font = font(.medium, 36)

    // MARK: –– Semibold
    static let semibold10: Font = font(.semibold, 10)
    static let semibold11: Font = font(.semibold, 11)
    static let semibold12: Font = font(.semibold, 12)
    static let semibold13: Font = font(.semibold, 13)
    static let semibold14: Font = font(.semibold, 14)
    static let semibold15: Font = font(.semibold, 15)
    static let semibold16: Font = font(.semibold, 16)
    static let semibold17: Font = font(.semibold, 17)
    static let semibold18: Font = font(.semibold, 18)
    static let semibold19: Font = font(.semibold, 19)
    static let semibold20: Font = font(.semibold, 20)
    static let semibold21: Font = font(.semibold, 21)
    static let semibold22: Font = font(.semibold, 22)
    static let semibold23: Font = font(.semibold, 23)
    static let semibold24: Font = font(.semibold, 24)
    static let semibold25: Font = font(.semibold, 25)
    static let semibold26: Font = font(.semibold, 26)
    static let semibold27: Font = font(.semibold, 27)
    static let semibold28: Font = font(.semibold, 28)
    static let semibold29: Font = font(.semibold, 29)
    static let semibold30: Font = font(.semibold, 30)
    static let semibold31: Font = font(.semibold, 31)
    static let semibold32: Font = font(.semibold, 32)
    static let semibold33: Font = font(.semibold, 33)
    static let semibold34: Font = font(.semibold, 34)
    static let semibold35: Font = font(.semibold, 35)
    static let semibold36: Font = font(.semibold, 36)

    // MARK: –– Bold
    static let bold10: Font = font(.bold, 10)
    static let bold11: Font = font(.bold, 11)
    static let bold12: Font = font(.bold, 12)
    static let bold13: Font = font(.bold, 13)
    static let bold14: Font = font(.bold, 14)
    static let bold15: Font = font(.bold, 15)
    static let bold16: Font = font(.bold, 16)
    static let bold17: Font = font(.bold, 17)
    static let bold18: Font = font(.bold, 18)
    static let bold19: Font = font(.bold, 19)
    static let bold20: Font = font(.bold, 20)
    static let bold21: Font = font(.bold, 21)
    static let bold22: Font = font(.bold, 22)
    static let bold23: Font = font(.bold, 23)
    static let bold24: Font = font(.bold, 24)
    static let bold25: Font = font(.bold, 25)
    static let bold26: Font = font(.bold, 26)
    static let bold27: Font = font(.bold, 27)
    static let bold28: Font = font(.bold, 28)
    static let bold29: Font = font(.bold, 29)
    static let bold30: Font = font(.bold, 30)
    static let bold31: Font = font(.bold, 31)
    static let bold32: Font = font(.bold, 32)
    static let bold33: Font = font(.bold, 33)
    static let bold34: Font = font(.bold, 34)
    static let bold35: Font = font(.bold, 35)
    static let bold36: Font = font(.bold, 36)
}
